language: swift
osx_image: xcode12.2

xcode_project: GithubSearch.xcodeproj
xcode_scheme: ios-swiftui-github-user-search
xcode_destination: platform=iOS Simulator,OS=14.2,name=iPhone 11

script:
  - xcodebuild -scheme ios-swiftui-github-user-search -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=14.2,name=iPhone 11' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
